repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: debug-statements
    -   id: requirements-txt-fixer

# Will enable black and flake8 in a future PR after fixing existing code
# -   repo: https://github.com/psf/black
#     rev: 23.3.0
#     hooks:
#     -   id: black
#         language_version: python3
# 
# -   repo: https://github.com/pycqa/flake8
#     rev: 6.0.0
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-docstrings]