[book]
title = "Whisper Voice Control Documentation"
authors = ["Project Contributors"]
description = "Documentation for Whisper Voice Control for macOS with Yabai"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/0xrin1/whisper-yabai-mac-os-x"
edit-url-template = "https://github.com/0xrin1/whisper-yabai-mac-os-x/edit/main/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html.fold]
enable = true
level = 1
