name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black==23.7.0 isort

    - name: Run flake8
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Check code formatting with black
      run: |
        python -m black --check src/ || echo "Black formatting issues found (not failing build)"

    - name: Check import order with isort
      run: |
        python -m isort --check-only --profile black src/ || echo "Import order issues found (not failing build)"
